### ISSUE TITLE
cannot build on Ubuntu 14.04

### ISSUE THREAD

**Issue by miches** [shellinabox/shellinabox#295] opened 2015-04-17 06:37 UTC
I tried to build the current sources according to the installation instructions for Debian, but "dpkg-buildpackage -b" fails. Here is the log output:

> dpkg-buildpackage: source package shellinabox
> dpkg-buildpackage: source version 2.14-1
> dpkg-buildpackage: source distribution unstable
> dpkg-buildpackage: source changed by Marc Singer <elf@debian.org>
> dpkg-buildpackage: host architecture amd64
> dpkg-source --before-build shellinabox
> debian/rules clean
> dh clean --with autotools-dev
> dh_testdir
> dh_auto_clean
> make[1]: Entering directory `/usr/src/shellinabox'
> cd . && automake-1.14 --gnu
> Makefile.am:5: error: Libtool library used but 'LIBTOOL' is undefined
> Makefile.am:5: The usual way to define 'LIBTOOL' is to add 'LT_INIT'
> Makefile.am:5: to 'configure.ac' and run 'aclocal' and 'autoconf' again.
> Makefile.am:5: If 'LT_INIT' is in 'configure.ac', make sure
> Makefile.am:5: its definition is in aclocal's search path.
> Makefile.am:76: warning: source file 'libhttp/hashmap.c' is in a subdirectory,
> Makefile.am:76: but option 'subdir-objects' is disabled
> automake-1.14: warning: possible forward-incompatibility.
> automake-1.14: At least a source file is in a subdirectory, but the 'subdir-objects'
> automake-1.14: automake option hasn't been enabled. For now, the corresponding output
> automake-1.14: object file(s) will be placed in the top-level directory. However,
> automake-1.14: this behaviour will change in future Automake versions: they will
> automake-1.14: unconditionally cause object files to be placed in the same subdirectory
> automake-1.14: of the corresponding sources.
> automake-1.14: You are advised to start using 'subdir-objects' option throughout your
> automake-1.14: project, to avoid future incompatibilities.
> Makefile.am:76: warning: source file 'libhttp/trie.c' is in a subdirectory,
> Makefile.am:76: but option 'subdir-objects' is disabled
> Makefile.am:76: warning: source file 'libhttp/httpconnection.c' is in a subdirectory,
> Makefile.am:76: but option 'subdir-objects' is disabled
> Makefile.am:76: warning: source file 'libhttp/server.c' is in a subdirectory,
> Makefile.am:76: but option 'subdir-objects' is disabled
> Makefile.am:76: warning: source file 'libhttp/ssl.c' is in a subdirectory,
> Makefile.am:76: but option 'subdir-objects' is disabled
> Makefile.am:76: warning: source file 'libhttp/url.c' is in a subdirectory,
> Makefile.am:76: but option 'subdir-objects' is disabled
> Makefile.am:65: warning: source file 'logging/logging.c' is in a subdirectory,
> Makefile.am:65: but option 'subdir-objects' is disabled
> Makefile.am:87: warning: source file 'shellinabox/shellinaboxd.c' is in a subdirectory,
> Makefile.am:87: but option 'subdir-objects' is disabled
> Makefile.am:87: warning: source file 'shellinabox/externalfile.c' is in a subdirectory,
> Makefile.am:87: but option 'subdir-objects' is disabled
> Makefile.am:87: warning: source file 'shellinabox/launcher.c' is in a subdirectory,
> Makefile.am:87: but option 'subdir-objects' is disabled
> Makefile.am:87: warning: source file 'shellinabox/privileges.c' is in a subdirectory,
> Makefile.am:87: but option 'subdir-objects' is disabled
> Makefile.am:87: warning: source file 'shellinabox/service.c' is in a subdirectory,
> Makefile.am:87: but option 'subdir-objects' is disabled
> Makefile.am:87: warning: source file 'shellinabox/session.c' is in a subdirectory,
> Makefile.am:87: but option 'subdir-objects' is disabled
> Makefile.am:87: warning: source file 'shellinabox/usercss.c' is in a subdirectory,
> Makefile.am:87: but option 'subdir-objects' is disabled
> make[1]: *** [Makefile.in] Error 1
> make[1]: Leaving directory `/usr/src/shellinabox'
> dh_auto_clean: make -j1 distclean returned exit code 2
> make: *** [clean] Error 2
> dpkg-buildpackage: error: debian/rules clean gave error exit status 2 

Please advise on how to proceed.

**Comment by KLuka** [comment] 2015-04-20 08:04
Hi, did you try to run command `autoreconf -i` before build?

And can you also check if you can build the binary with make command?

**Comment by gdm85** [comment] 2015-04-21 10:23
I also have a build failure on same system:

https://gist.github.com/gdm85/eee1126c5f42ec201828

**Comment by gdm85** [comment] 2015-04-21 10:29
If I install automake/autoconf and add ``autoreconf -i`` before ``make``, then I get:

```
configure.ac:17: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by KLuka** [comment] 2015-04-21 10:40
Hi @gdm85, I think that you need to add `-b` switch to `dpkg-buildpackage` command.

**Comment by gdm85** [comment] 2015-04-21 10:43
@KLuka ok, thanks! That solved the issue. I reported it here because with original shellinabox it does not try to include the source by default.

**Comment by KLuka** [comment] 2015-04-21 10:49
No problem :) 

The cause for this is file `debian/source/format`. But I don't know if it is smart to remove it. Maybe @beewoolie will know more about this...

**Comment by gdm85** [comment] 2015-04-21 11:11
@KLuka if it's a new Debian best practice then I think it should stay as is now

**Comment by miches** [comment] 2015-04-21 22:32
@KLuka :

Running autoreconf -i throws a ton of warnings, but doesn't fail.

> libtoolize: putting auxiliary files in `.'.
> libtoolize: copying file `./ltmain.sh'
> libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
> libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree.
> libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
> configure.ac:14: installing './compile'
> Makefile.am:76: warning: source file 'libhttp/hashmap.c' is in a subdirectory,
> Makefile.am:76: but option 'subdir-objects' is disabled
> automake: warning: possible forward-incompatibility.
> automake: At least a source file is in a subdirectory, but the 'subdir-objects'
> automake: automake option hasn't been enabled.  For now, the corresponding output
> automake: object file(s) will be placed in the top-level directory.  However,
> automake: this behaviour will change in future Automake versions: they will
> automake: unconditionally cause object files to be placed in the same subdirectory
> automake: of the corresponding sources.
> automake: You are advised to start using 'subdir-objects' option throughout your
> automake: project, to avoid future incompatibilities.
> Makefile.am:76: warning: source file 'libhttp/trie.c' is in a subdirectory,
> Makefile.am:76: but option 'subdir-objects' is disabled
> Makefile.am:76: warning: source file 'libhttp/httpconnection.c' is in a subdirectory,
> Makefile.am:76: but option 'subdir-objects' is disabled
> Makefile.am:76: warning: source file 'libhttp/server.c' is in a subdirectory,
> Makefile.am:76: but option 'subdir-objects' is disabled
> Makefile.am:76: warning: source file 'libhttp/ssl.c' is in a subdirectory,
> Makefile.am:76: but option 'subdir-objects' is disabled
> Makefile.am:76: warning: source file 'libhttp/url.c' is in a subdirectory,
> Makefile.am:76: but option 'subdir-objects' is disabled
> Makefile.am:65: warning: source file 'logging/logging.c' is in a subdirectory,
> Makefile.am:65: but option 'subdir-objects' is disabled
> Makefile.am:87: warning: source file 'shellinabox/shellinaboxd.c' is in a subdirectory,
> Makefile.am:87: but option 'subdir-objects' is disabled
> Makefile.am:87: warning: source file 'shellinabox/externalfile.c' is in a subdirectory,
> Makefile.am:87: but option 'subdir-objects' is disabled
> Makefile.am:87: warning: source file 'shellinabox/launcher.c' is in a subdirectory,
> Makefile.am:87: but option 'subdir-objects' is disabled
> Makefile.am:87: warning: source file 'shellinabox/privileges.c' is in a subdirectory,
> Makefile.am:87: but option 'subdir-objects' is disabled
> Makefile.am:87: warning: source file 'shellinabox/service.c' is in a subdirectory,
> Makefile.am:87: but option 'subdir-objects' is disabled
> Makefile.am:87: warning: source file 'shellinabox/session.c' is in a subdirectory,
> Makefile.am:87: but option 'subdir-objects' is disabled
> Makefile.am:87: warning: source file 'shellinabox/usercss.c' is in a subdirectory,
> Makefile.am:87: but option 'subdir-objects' is disabled

After that, make (and also dpkg-buildpackage -b) work as well.

**Comment by miches** [comment] 2015-04-21 22:41
Should this version work with all keys in a current firefox browser? I have installed it, but '-' , '|' , '#', '+' and a bunch of other keys still just do nothing.

**Comment by KLuka** [comment] 2015-04-21 22:55
@miches yes it should... And it does for what I have tested :)

Did you refreshed your browser after instalation and what language are you using?

**Comment by miches** [comment] 2015-04-22 08:01
Yes, I did. Today, after I also restarted Firefox instead of just reloading, it works, however. 

But not completely. On my German keyboard, the +/* and </> keys (plus ß/?) are still dead.

**Comment by KLuka** [comment] 2015-04-22 08:26
Ok, that is probably the case because I haven't tested this :) Could you write me keycodes for these keys and I will have a look...

You can use this website: http://www.asquare.net/javascript/tests/KeyCode.html

**Comment by miches** [comment] 2015-04-22 08:54
The +/* key (on which ~ is selectable via AltGr) has a key code of 171. </> (with ¦ on AltGr) is 60, and ß/?  ( \ on AltGr) is 63.

**Comment by KLuka** [comment] 2015-04-22 10:36
@miches ok I tested this and the keys `|`, `\` and `~` are really not working on German keyboard :( 

For now you can select option "Disable Alt Key" from context menu and they will start to work. I will try to fix this as soon as possible.

**Comment by KLuka** [comment] 2015-04-22 19:44
@miches I reworked some keyboard handling code. Tests with German layout were successful, so you check the latest sources.

I am also closing this issue for now.

**Closed by KLuka** 2015-04-22 19:44 UTC
Labels: keyboard, support
