### ISSUE TITLE
French keyboard issue : no more / : * $ < >

### ISSUE THREAD

**Issue by lokiiiii** [shellinabox/shellinabox#305] opened 2015-05-13 09:55 UTC
Hello,
I'm sorry to open a new issue, I've already read a lot of answers here about the keywords that aren't working but I couldn't find a fix so...
I've updated shellinabox yesterday and now I can't use " / " or " : " or " < " or " > " anymore so it's obviously pretty annoying.
I'm using a french keyboard with LC_ALL & LANGUAGE set to fr_FR.utf-8
Is there a way to fix this ?
Thanks so much!

**Comment by KLuka** [comment] 2015-05-13 10:18
I tested it again with FR - French (France) keyboard and all the keys should work fine. I assume that you are using Firefox. What version of shellinabox are you using (context menu > about).  My first advice is to refresh your browser with Ctrl+F5 and try again...

**Comment by lokiiiii** [comment] 2015-05-13 10:41
First of all, thanks for your quick answer! =)
That's pretty weird: I tested from home under Chrome and you're right, everything works fine!
When I'm at work, I'm using Firefox through FreeNX and I think that this Firefox is configured as en_US so my shellinabox doesn't seem to recognise the layout...
Is there a way to force the keyboard layout ?

**Comment by KLuka** [comment] 2015-05-13 11:06
No problem :) This type of issues were related to Firefox. Could you test from home with Firefox browser and please check shellianbox version writen in context menu (right click > About...). It should say 2.15

**Comment by lokiiiii** [comment] 2015-05-13 11:13
it is v2.10 build 239. I upgraded it yesterday at night...

**Comment by KLuka** [comment] 2015-05-13 11:19
Uffff, this is old version :) you have to build new version from sources of this repo and than install it. For details please see README.md file. If you don't want to do that you can use Chrome browser and it will work fine.

I will close this issue as already solved and duplicate of #202

**Closed by KLuka** 2015-05-13 11:19 UTC

**Comment by lokiiiii** [comment] 2015-05-13 11:21
wow, so sorry xD
I really don't mind building a new version, I just didn't know it was so old :)
Thanks a lot!

**Comment by lokiiiii** [comment] 2015-05-13 11:24
Just one more thing: is it possible to either remove the old installation or move the whole shellinabox directory somewhere else than where it was previously installed ?
Thanks =)

**Comment by KLuka** [comment] 2015-05-13 11:35
I think that you could move /usr/bin/shellinaboxd to /usr/bin/shellinaboxd.old or something like that and then reinstall new .deb package. I didn't try this, but I think it should work :)

**Comment by lokiiiii** [comment] 2015-05-13 11:59
Thanks again :)

PS: last version works GREAT :D

**Comment by KLuka** [comment] 2015-05-13 11:59
NP, and thanks for the feedback :+1:

**Comment by a-detiste** [comment] 2015-05-13 15:42
>  move the whole shellinabox directory

files doesn't get installed in single directory per package; but are spread around.
`dpkg -L shellinabox`will tell you what files belongs to siab.

`dpkg --verify shellinabox` will list the files from this list that have been modified since installation
